# Generated by Django 3.2.6 on 2021-08-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
