# Generated by Django 3.2.6 on 2021-08-12 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lepak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='lepak.profile'),
        ),
    ]
