# Generated by Django 3.2.6 on 2021-08-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepak', '0002_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
