# Generated by Django 3.2.6 on 2021-08-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepak', '0003_alter_journal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='entry',
            field=models.TextField(blank=True),
        ),
    ]
