# Generated by Django 3.2.6 on 2021-08-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepak', '0004_alter_journal_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
